# Generated by Django 3.2.3 on 2021-06-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_home', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_desc',
            field=models.TextField(default=models.CharField(max_length=100)),
        ),
    ]
