# Generated by Django 3.2.3 on 2021-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_home', '0006_categories_cat_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
